### ISSUE TITLE
Stack creation fails with "Attribute: PublicIp was not found for resource" when assignStaticIP parameter is "No"

### ISSUE THREAD

**Issue by elduds** [aws-samples/amazon-ec2-nice-dcv-samples#2]
https://github.com/aws-samples/amazon-ec2-nice-dcv-samples/blob/c0b9957144b7b1d5b477216742ed9c3f346a60b2/cfn/AmazonLinux2-NICE-DCV.yaml#L535

Suggest adding a condition to the output eg.
```yaml
  DCVwebConsole:
    Condition: useElasticIP
    Description: DCV web console (login as ec2-user)
    Value: !Sub "https://${ec2Instance.PublicIp}:${listenPort}"
```
