### ISSUE TITLE
Parametrize DisableApiTermination in CF template(s)

### ISSUE THREAD

**Issue by ruzickap** [aws-samples/amazon-ec2-nice-dcv-samples#8]
Hello.

I can see, the `DisableApiTermination` was [added](https://github.com/aws-samples/amazon-ec2-nice-dcv-samples/commit/d0ed9942943982be44ff6e26ceeaa337dd19c596#diff-c948fe12cd8df0c65a13dfff5cc714e36b58bbe05b37960dd640a075b1efa3d3) to the CF templates.

Would'n it make sense to parametrize it?

```yaml
  disableApiTermination:
    Type: String
    Description: Disable API termination for the EC2 instance
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
```

When I would like to create + delete the CF template - it can not be easily done. I need to do ["extra" steps for EC2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_ChangingDisableAPITermination.html).

Thanks for considering it.

**Comment by limmike** [comment]
Hello,


This was added after recent security code review, where cfn_nag flagged the lack of EC2 termination protection as a finding. 

There was also an incident, where a customer inadvertently terminated his EC2 instance and lost months of production data. 
To prevent future incidents, I rather customers explicitly disable termination protection manually before deleting their EC2 instances. 

As I [recall](https://github.com/aws-samples/amazon-ec2-nice-dcv-samples/issues/4#issuecomment-2087859013) when we add `allowWebServerPorts` ,  I also include [CloudFormation exports](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html) `<Stack Name>-InstanceID` .  With Instance ID value, we can easily use AWS CLI to disable termination protection as follows

```
aws ec2 modify-instance-attribute  --disable-api-termination Value=true --instance-id <instanceID>
```

Will this work for you?

**Comment by ruzickap** [comment]
Yeah...

It's ok to add "EC2 termination protection" to CF template and make it default, but it would be nice to have it parametrized - to allow people to turn it off easily (rather than "hardcode" it).

* I would still prefer to use CF parameters, because it is much easier + user friendly to simply use `rain deploy ...` + `rain rm ...` without any additional complexity...

* The AWS Console users should be allowed to easily deploy the CF template + Delete it without "any effort"...

**Comment by limmike** [comment]
Valid points. 

Will add it in later this week.  Something like this 

```
  ec2TerminationProtection:
    Type: String
    Description: Enable EC2 termination protection to prevent accidental deletion
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"
```
